[package]
name = "audioipc-server"
version = "0.2.3"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Remote cubeb server"

[dependencies]
audioipc = { path = "../audioipc" }
cubeb-core = "0.5.4"
bytes = "0.4"
lazycell = "^0.4"
libc = "0.2"
log = "0.4"
slab = "0.4.3"
futures = "0.3.15"
tokio-core = "0.1"
tokio-uds = "0.2.5"
lazy_static = "1.4.0"

[dependencies.error-chain]
version = "0.11.0"
default-features = false
