[workspace]
members = [
    "direct-composition",
    "examples",
    "webrender",
    "webrender_api",
    "wrench",
    "example-compositor/compositor",
]

[profile.release]
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
